import os

FOOTER = '''        <div className="mt-8 pt-6 border-t border-gray-100 text-center">
          <p className="text-xs text-gray-400">Built by Marco Costa &middot; For portfolio demonstration purposes</p>
          <Link href="/privacy-policy" className="text-xs text-gray-400 hover:text-gray-600 underline">Privacy Policy</Link>
        </div>'''

# ============================================================
# page.tsx (home)
# ============================================================
path1 = r"C:\Projetos\contract-analyser\src\app\page.tsx"
with open(path1, 'r', encoding='utf-8') as f:
    c = f.read()

c = c.replace(
    '        <div className="mt-8 pt-6 border-t border-gray-100 text-center">\n          <p className="text-xs text-gray-400">Built by Marco Costa</p>\n          <Link href="/privacy-policy" className="text-xs text-gray-400 hover:text-gray-600 underline">Privacy Policy</Link>\n        </div>',
    FOOTER
)
with open(path1, 'w', encoding='utf-8') as f:
    f.write(c)
print("page.tsx footer actualizado.")

# ============================================================
# acesso/page.tsx
# ============================================================
path2 = r"C:\Projetos\contract-analyser\src\app\acesso\page.tsx"
with open(path2, 'r', encoding='utf-8') as f:
    c = f.read()

c = c.replace(
    '        <div className="mt-8 pt-6 border-t border-gray-100 text-center">\n          <p className="text-xs text-gray-400">Built by Marco Costa</p>\n          <Link href="/privacy-policy" className="text-xs text-gray-400 hover:text-gray-600 underline">Privacy Policy</Link>\n        </div>',
    FOOTER
)
with open(path2, 'w', encoding='utf-8') as f:
    f.write(c)
print("acesso/page.tsx footer actualizado.")

# ============================================================
# analisar/page.tsx — fix footer + remove disclaimer do Claude
# ============================================================
path3 = r"C:\Projetos\contract-analyser\src\app\analisar\page.tsx"
with open(path3, 'r', encoding='utf-8') as f:
    c = f.read()

# Fix footer
old_footer = '        <div className="mt-8 text-center">\n          <p className="text-xs text-gray-400">Built by Marco Costa</p>\n          <Link href="/privacy-policy" className="text-xs text-gray-400 hover:text-gray-600 underline">Privacy Policy</Link>\n        </div>'
if old_footer in c:
    c = c.replace(old_footer, FOOTER)
    print("analisar/page.tsx footer actualizado.")
else:
    print("analisar/page.tsx footer - padrao nao encontrado, a tentar alternativo...")
    c = c.replace('Built by Marco Costa &middot; Legal Engineer Portfolio', 'Built by Marco Costa &middot; For portfolio demonstration purposes')
    c = c.replace('Legal Engineer Portfolio', 'For portfolio demonstration purposes')

with open(path3, 'w', encoding='utf-8') as f:
    f.write(c)

# ============================================================
# analisar/route.ts — remove disclaimer do prompt do Claude
# ============================================================
path4 = r"C:\Projetos\contract-analyser\src\app\api\analisar\route.ts"
with open(path4, 'r', encoding='utf-8') as f:
    c = f.read()

old_disclaimer = r"""\u26a0\ufe0f DISCLAIMER: This analysis is generated by AI for informational purposes only. It does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified lawyer."""
if old_disclaimer in c:
    c = c.replace(old_disclaimer, '')
    print("route.ts disclaimer removido do prompt.")
else:
    # try alternate
    c = c.replace('\\u26a0\\ufe0f DISCLAIMER: This analysis is generated by AI for informational purposes only. It does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified lawyer.', '')
    print("route.ts disclaimer - tentativa alternativa aplicada.")

with open(path4, 'w', encoding='utf-8') as f:
    f.write(c)

print("Todos os ficheiros actualizados.")
