import os

path = r"C:\Projetos\contract-analyser\src\app\api\analisar\route.ts"
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

old_fn = """function generateTechSheetPdf(): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = 210
  const margin = 22
  const contentWidth = pageWidth - margin * 2
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://contract-analyser.vercel.app'

  let y = 24

  doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(17, 24, 39)
  doc.text('CONTRACT ANALYSER APP', pageWidth / 2, y, { align: 'center' }); y += 6
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(107, 114, 128)
  doc.text('Technical Overview  \\u00b7  Built by Marco Costa', pageWidth / 2, y, { align: 'center' }); y += 7
  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 8

  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(75, 85, 99)
  const desc = 'A full-stack web application that allows users to upload contract PDFs and receive a structured legal analysis generated by AI. Built as a portfolio demonstration of legal engineering and software development skills.'
  const descLines = doc.splitTextToSize(desc, contentWidth)
  doc.text(descLines, margin, y); y += descLines.length * 4.5 + 8

  const section = (title: string) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(29, 78, 216)
    doc.text(title.toUpperCase(), margin, y); y += 1.5
    doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 5
  }

  const item = (label: string, detail: string) => {
    const colLabel = 52
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(17, 24, 39)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(75, 85, 99)
    const detailLines = doc.splitTextToSize(detail, contentWidth - colLabel)
    doc.text(detailLines, margin + colLabel, y); y += detailLines.length * 4.5 + 1.5
  }

  section('Frontend')
  item('Next.js 14', 'React framework with App Router, Server Components and API Routes')
  item('TypeScript', 'Typed JavaScript for reliability and maintainability')
  item('Tailwind CSS', 'Utility-first CSS framework for responsive design')
  item('React Markdown', 'Renders structured markdown output from Claude API')
  y += 4

  section('Backend & API')
  item('Next.js API Routes', 'Server-side endpoints for analysis, access control and email dispatch')
  item('Anthropic Claude API', 'claude-opus-4-5 \\u2014 native PDF reading, structured legal analysis')
  item('Resend', 'Transactional email delivery (access code + analysis PDF)')
  item('jsPDF', 'Server-side PDF generation for analysis report and technical sheet')
  y += 4

  section('Infrastructure & Data')
  item('Vercel', 'Deployment platform with serverless functions and daily cron job')
  item('Supabase', 'PostgreSQL database (access codes, analyses) and file storage (PDFs)')
  item('Supabase Storage', 'Secure private bucket for uploaded contract PDFs (max 20 MB)')
  y += 4

  section('Key Features')
  const features = [
    'Access control via professional email + one-time code',
    'Email domain validation \\u2014 blocks personal email providers',
    'Native PDF reading by Claude (no intermediate text extraction)',
    'Structured legal analysis across 8 sections',
    'Automatic PDF generation and email delivery to user',
    'Usage limits enforced per access code',
    'Automated data retention: analyses deleted after 3 days, codes after 30 days',
    'Admin panel with usage tracking and CSV export',
  ]
  for (const f of features) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(55, 65, 81)
    doc.text('\\u2022', margin, y)
    const wrapped = doc.splitTextToSize(f, contentWidth - 5)
    doc.text(wrapped, margin + 5, y); y += wrapped.length * 4.5 + 1
  }
  y += 4

  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 5
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(156, 163, 175)
  doc.text('Built by Marco Costa  \\u00b7  Legal Engineer  \\u00b7  For portfolio demonstration purposes', pageWidth / 2, y, { align: 'center' }); y += 4
  doc.setTextColor(29, 78, 216)
  doc.textWithLink(appUrl, pageWidth / 2, y, { url: appUrl, align: 'center' } as any)

  return Buffer.from(doc.output('arraybuffer'))
}"""

new_fn = """function generateTechSheetPdf(): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = 210
  const margin = 22
  const contentWidth = pageWidth - margin * 2
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://contract-analyser-iota.vercel.app'

  let y = 24

  // Header
  doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(17, 24, 39)
  doc.text('CONTRACT ANALYSER APP', pageWidth / 2, y, { align: 'center' }); y += 6
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(107, 114, 128)
  doc.text('Technical Overview  \u00b7  Built by Marco Costa', pageWidth / 2, y, { align: 'center' }); y += 7
  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 8

  // Description
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(75, 85, 99)
  const desc = 'A full-stack web application that allows users to upload contract PDFs and receive a structured legal analysis generated by AI. Built as a portfolio demonstration of legal engineering and software development skills.'
  const descLines = doc.splitTextToSize(desc, contentWidth)
  doc.text(descLines, margin, y); y += descLines.length * 4.5 + 8

  // ── Flow diagram section heading ──
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(29, 78, 216)
  doc.text('APPLICATION FLOW', margin, y); y += 1.5
  doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 6

  // Flow diagram constants
  const bh = 10    // box height mm
  const br = 2     // box corner radius
  const fs = 7     // font size in boxes
  const lh = 16    // row height (box + gap)
  const c1x = margin + 10
  const c1w = 36
  const g1  = 6
  const c2x = c1x + c1w + g1
  const c2w = 48
  const g2  = 6
  const c3x = c2x + c2w + g2
  const c3w = 54

  const r1y = y
  const r2y = y + lh
  const r3y = y + lh * 2
  const r4y = y + lh * 3

  // Layer label helper
  const layerLabel = (label: string, ry: number) => {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(6); doc.setTextColor(180, 180, 180)
    doc.text(label, margin, ry + bh / 2, { baseline: 'middle' })
  }

  // Box helper
  const box = (x: number, bw: number, by: number, label: string, sub: string | null,
    blue: boolean, purple: boolean, teal: boolean, amber: boolean) => {
    if (blue)        { doc.setFillColor(219, 234, 254); doc.setDrawColor(147, 197, 253) }
    else if (purple) { doc.setFillColor(237, 233, 254); doc.setDrawColor(196, 181, 253) }
    else if (teal)   { doc.setFillColor(209, 250, 229); doc.setDrawColor(110, 231, 183) }
    else if (amber)  { doc.setFillColor(254, 243, 199); doc.setDrawColor(252, 211, 77)  }
    else             { doc.setFillColor(243, 244, 246); doc.setDrawColor(209, 213, 219) }
    doc.roundedRect(x, by, bw, bh, br, br, 'FD')
    doc.setFont('helvetica', 'bold'); doc.setFontSize(fs)
    if (blue)        doc.setTextColor(30, 64, 175)
    else if (purple) doc.setTextColor(109, 40, 217)
    else if (teal)   doc.setTextColor(4, 120, 87)
    else if (amber)  doc.setTextColor(146, 64, 14)
    else             doc.setTextColor(55, 65, 81)
    const ty = sub ? by + 3.5 : by + bh / 2
    doc.text(label, x + bw / 2, ty, { align: 'center', baseline: 'middle' })
    if (sub) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(107, 114, 128)
      doc.text(sub, x + bw / 2, by + 7, { align: 'center', baseline: 'middle' })
    }
  }

  // Horizontal arrow — label below
  const arrowH = (x1: number, x2: number, ay: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(x1, ay, x2 - 1, ay)
    doc.setFillColor(156, 163, 175)
    doc.triangle(x2, ay, x2 - 2, ay - 1, x2 - 2, ay + 1, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, (x1 + x2) / 2, ay + 2.5, { align: 'center' })
    }
    doc.setLineWidth(0.2)
  }

  // Vertical arrow — label to the right
  const arrowV = (ax: number, y1: number, y2: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(ax, y1, ax, y2 - 1)
    doc.setFillColor(156, 163, 175)
    doc.triangle(ax, y2, ax - 1, y2 - 2, ax + 1, y2 - 2, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, ax + 2, (y1 + y2) / 2, { align: 'left', baseline: 'middle' })
    }
    doc.setLineWidth(0.2)
  }

  // Left-pointing arrow — label below
  const arrowLeft = (x1: number, x2: number, ay: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(x1, ay, x2 + 1, ay)
    doc.setFillColor(156, 163, 175)
    doc.triangle(x2, ay, x2 + 2, ay - 1, x2 + 2, ay + 1, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, (x1 + x2) / 2, ay + 2.5, { align: 'center' })
    }
    doc.setLineWidth(0.2)
  }

  doc.setLineWidth(0.2)

  // ROW 1 — Access
  layerLabel('Access', r1y)
  box(c1x, c1w, r1y, 'User', null, false, false, false, false)
  arrowH(c1x + c1w, c2x, r1y + bh / 2, 'email')
  box(c2x, c2w, r1y, 'Resend', 'sends access code', true, false, false, false)
  arrowH(c2x + c2w, c3x, r1y + bh / 2, 'access code')
  box(c3x, c3w, r1y, 'Supabase DB', 'stores access_codes', false, false, true, false)

  // ROW 2 — Analysis
  layerLabel('Analysis', r2y)
  arrowV(c1x + c1w / 2, r1y + bh, r2y, 'code + PDF')
  box(c1x, c1w, r2y, 'Next.js API', '/api/analisar', false, false, false, false)
  arrowH(c1x + c1w, c2x, r2y + bh / 2, 'validate')
  box(c2x, c2w, r2y, 'Supabase DB', 'checks code + count', false, false, true, false)
  arrowH(c2x + c2w, c3x, r2y + bh / 2, 'PDF')
  box(c3x, c3w, r2y, 'Anthropic API', 'Claude analyses PDF', false, true, false, false)

  // ROW 3 — Delivery
  layerLabel('Delivery', r3y)
  arrowV(c3x + c3w / 2, r2y + bh, r3y, 'analysis')
  box(c3x, c3w, r3y, 'jsPDF', 'generates PDF report', false, false, false, false)
  arrowLeft(c3x, c2x + c2w, r3y + bh / 2, 'PDF')
  box(c2x, c2w, r3y, 'Resend', 'emails PDF to user', true, false, false, false)
  arrowLeft(c2x, c1x + c1w, r3y + bh / 2, null)
  box(c1x, c1w, r3y, 'User inbox', 'analysis + tech', false, false, false, false)

  // ROW 4 — Storage
  layerLabel('Storage', r4y)
  arrowV(c1x + c1w / 2, r2y + bh, r4y, null)
  box(c1x, c1w, r4y, 'Supabase Storage', 'contract PDF', false, false, true, false)
  arrowH(c1x + c1w, c2x, r4y + bh / 2, null)
  box(c2x, c2w, r4y, 'Supabase DB', 'saves analysis', false, false, true, false)
  // dashed arrow to cron
  doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
  doc.setLineDashPattern([1, 1], 0)
  doc.line(c2x + c2w, r4y + bh / 2, c3x - 1, r4y + bh / 2)
  doc.setLineDashPattern([], 0)
  doc.setFillColor(156, 163, 175)
  doc.triangle(c3x, r4y + bh / 2, c3x - 2, r4y + bh / 2 - 1, c3x - 2, r4y + bh / 2 + 1, 'F')
  doc.setLineWidth(0.2)
  box(c3x, c3w, r4y, 'Vercel cron', 'deletes 3d / 30d', false, false, false, true)

  y = r4y + bh + 8

  // ── Tech stack sections ──
  const section = (title: string) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(29, 78, 216)
    doc.text(title.toUpperCase(), margin, y); y += 1.5
    doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 5
  }

  const item = (label: string, detail: string) => {
    const colLabel = 52
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(17, 24, 39)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(75, 85, 99)
    const detailLines = doc.splitTextToSize(detail, contentWidth - colLabel)
    doc.text(detailLines, margin + colLabel, y); y += detailLines.length * 4.5 + 1.5
  }

  section('Frontend')
  item('Next.js 14', 'React framework with App Router, Server Components and API Routes')
  item('TypeScript', 'Typed JavaScript for reliability and maintainability')
  item('Tailwind CSS', 'Utility-first CSS framework for responsive design')
  item('React Markdown', 'Renders structured markdown output from Claude API')
  y += 3

  section('Backend & API')
  item('Next.js API Routes', 'Server-side endpoints for analysis, access control and email dispatch')
  item('Anthropic Claude API', 'claude-opus-4-5 \u2014 native PDF reading, structured legal analysis')
  item('Resend', 'Transactional email delivery (access code + analysis PDF)')
  item('jsPDF', 'Server-side PDF generation for analysis report and technical sheet')
  y += 3

  section('Infrastructure & Data')
  item('Vercel', 'Deployment platform with serverless functions and daily cron job')
  item('Supabase', 'PostgreSQL database (access codes, analyses) and file storage (PDFs)')
  item('Supabase Storage', 'Secure private bucket for uploaded contract PDFs (max 20 MB)')
  y += 3

  section('Key Features')
  const features = [
    'Access control via professional email + one-time code',
    'Email domain validation \u2014 blocks personal email providers',
    'Native PDF reading by Claude (no intermediate text extraction)',
    'Structured legal analysis across 8 sections',
    'Automatic PDF generation and email delivery to user',
    'Usage limits enforced per access code',
    'Automated data retention: analyses deleted after 3 days, codes after 30 days',
    'Admin panel with usage tracking and CSV export',
  ]
  for (const f of features) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(55, 65, 81)
    doc.text('\u2022', margin, y)
    const wrapped = doc.splitTextToSize(f, contentWidth - 5)
    doc.text(wrapped, margin + 5, y); y += wrapped.length * 4.5 + 1
  }
  y += 4

  // Footer
  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 5
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(156, 163, 175)
  doc.text('Built by Marco Costa  \u00b7  Legal Engineer  \u00b7  For portfolio demonstration purposes', pageWidth / 2, y, { align: 'center' }); y += 4
  doc.setTextColor(29, 78, 216)
  doc.textWithLink(appUrl, pageWidth / 2, y, { url: appUrl, align: 'center' } as any)

  return Buffer.from(doc.output('arraybuffer'))
}"""

if old_fn in content:
    content = content.replace(old_fn, new_fn)
    print("Substituicao OK")
else:
    print("ERRO: padrao nao encontrado")
    exit(1)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f"OK: {path}")
print("Fix concluido.")
