import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import Anthropic from '@anthropic-ai/sdk'
import { Resend } from 'resend'
import { jsPDF } from 'jspdf'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const resend = new Resend(process.env.RESEND_API_KEY)

function generateAnalysisPdf(analysisText: string, generatedDate: string): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = 210
  const margin = 22
  const contentWidth = pageWidth - margin * 2
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://contract-analyser.vercel.app'
  const footerY = 278

  let y = 20

  const addPage = () => { doc.addPage(); y = 20 }
  const checkPageBreak = (needed: number) => { if (y + needed > 262) addPage() }

  const cleanText = (text: string) =>
    text
      .replace(/\u26a0\ufe0f/g, '[!]')
      .replace(/\u26a0/g, '[!]')
      .replace(/[\u{1F7E2}\u{1F7E1}\u{1F534}]/gu, '')

  const stripBold = (text: string) => text.replace(/\*\*/g, '')

  const drawFooter = () => {
    const total = doc.getNumberOfPages()
    for (let p = 1; p <= total; p++) {
      doc.setPage(p)
      if (p === total) {
        doc.setDrawColor(229, 231, 235)
        doc.line(margin, footerY - 10, pageWidth - margin, footerY - 10)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(7)
        doc.setTextColor(156, 163, 175)
        doc.text('Disclaimer:', margin, footerY - 6)
        doc.setFont('helvetica', 'normal')
        const disclaimer = 'This analysis is generated by AI for informational purposes only. It does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified lawyer.'
        const dLines = doc.splitTextToSize(disclaimer, contentWidth - 20)
        doc.text(dLines, margin + 20, footerY - 6)
        const builtY = footerY - 6 + dLines.length * 3.2 + 3.5
        const prefix = 'Built by Marco Costa  \u00b7  For portfolio demonstration purposes  \u00b7  '
        const linkLabel = 'Privacy Policy'
        const totalWidth = doc.getTextWidth(prefix + linkLabel)
        const startX = (pageWidth - totalWidth) / 2
        doc.setTextColor(156, 163, 175)
        doc.text(prefix, startX, builtY)
        doc.setTextColor(29, 78, 216)
        doc.textWithLink(linkLabel, startX + doc.getTextWidth(prefix), builtY, { url: `${appUrl}/privacy-policy` })
      }
    }
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(17, 24, 39)
  doc.text('CONTRACT ANALYSER APP', pageWidth / 2, y, { align: 'center' })
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(107, 114, 128)
  doc.text(`Analysis Report  \u00b7  Generated on ${generatedDate}`, pageWidth / 2, y, { align: 'center' })
  y += 7
  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  const lines = cleanText(analysisText).split('\n')

  for (const raw of lines) {
    const line = raw.trim()
    if (line === '') { y += 2; continue }
    if (line === '---') {
      checkPageBreak(6)
      doc.setDrawColor(243, 244, 246)
      doc.line(margin, y, pageWidth - margin, y)
      y += 5; continue
    }
    if (line.startsWith('## ')) {
      const text = line.replace(/^## /, '').toUpperCase()
      checkPageBreak(12); y += 3
      doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(29, 78, 216)
      doc.text(text, margin, y); y += 1.5
      doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 5; continue
    }
    if (line.startsWith('# ')) {
      const text = stripBold(line.replace(/^# /, ''))
      checkPageBreak(10)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(17, 24, 39)
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y); y += wrapped.length * 5.5 + 3; continue
    }
    if (line.startsWith('- ')) {
      const text = line.replace(/^- /, '')
      checkPageBreak(6)
      if (text.startsWith('[!]')) {
        const alertLabel = '[!] Alert:'
        // Remove qualquer prefixo [!] extra e asteriscos, ficando só com o texto limpo
        const rest = text.replace(/^\[!\]\s*/i, '').replace(/^\*?\*?Alert:\*?\*?\s*/i, '').replace(/^\[!\]\s*/i, '').replace(/\*\*/g, '').trim()
        const fullText = `${alertLabel}  ${rest}`
        const wrapped = doc.splitTextToSize(fullText, contentWidth - 5)
        doc.setFontSize(8.5)
        const labelWidth = doc.getTextWidth(alertLabel + '  ')
        doc.setFont('helvetica', 'bold'); doc.setTextColor(234, 88, 12)
        doc.text(alertLabel, margin + 5, y)
        doc.setFont('helvetica', 'normal'); doc.setTextColor(55, 65, 81)
        doc.text(wrapped[0].replace(alertLabel + '  ', ''), margin + 5 + labelWidth, y)
        for (let wl = 1; wl < wrapped.length; wl++) { y += 4.5; doc.text(wrapped[wl], margin + 5, y) }
        y += 5; continue
      }
      doc.setFontSize(8.5); doc.setTextColor(55, 65, 81)
      doc.text('\u2022', margin, y)
      const plainText = stripBold(text)
      const wrapped = doc.splitTextToSize(plainText, contentWidth - 5)
      if (text.includes('**')) {
        const parts = text.split(/\*\*/)
        let x = margin + 5
        for (let p = 0; p < parts.length; p++) {
          if (!parts[p]) continue
          doc.setFont('helvetica', p % 2 === 1 ? 'bold' : 'normal')
          const w = doc.getTextWidth(parts[p])
          if (x + w > pageWidth - margin) break
          doc.text(parts[p], x, y); x += w
        }
        if (wrapped.length > 1) {
          for (let wl = 1; wl < wrapped.length; wl++) { y += 4.5; doc.setFont('helvetica', 'normal'); doc.text(wrapped[wl], margin + 5, y) }
        }
      } else {
        doc.setFont('helvetica', 'normal'); doc.text(wrapped, margin + 5, y)
      }
      y += wrapped.length * 4.5 + 1; continue
    }
    if (line.startsWith('**') && line.endsWith('**') && line.length > 4) {
      const text = stripBold(line)
      checkPageBreak(7)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(17, 24, 39)
      const wrapped = doc.splitTextToSize(text, contentWidth)
      doc.text(wrapped, margin, y); y += wrapped.length * 5 + 2; continue
    }
    if (line.startsWith('**')) {
      checkPageBreak(7); doc.setFontSize(9); doc.setTextColor(17, 24, 39)
      const parts = line.split(/\*\*/)
      let x = margin
      for (let p = 0; p < parts.length; p++) {
        if (!parts[p]) continue
        doc.setFont('helvetica', p % 2 === 1 ? 'bold' : 'normal')
        if (x + doc.getTextWidth(parts[p]) > pageWidth - margin) break
        doc.text(parts[p], x, y); x += doc.getTextWidth(parts[p])
      }
      const plain = doc.splitTextToSize(stripBold(line), contentWidth)
      if (plain.length > 1) {
        for (let wl = 1; wl < plain.length; wl++) { y += 5; doc.setFont('helvetica', 'normal'); doc.text(plain[wl], margin, y) }
      }
      y += 5.5; continue
    }
    checkPageBreak(6)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(55, 65, 81)
    const wrapped = doc.splitTextToSize(line, contentWidth)
    doc.text(wrapped, margin, y); y += wrapped.length * 4.5 + 1
  }

  drawFooter()
  return Buffer.from(doc.output('arraybuffer'))
}

function generateTechSheetPdf(): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = 210
  const margin = 22
  const contentWidth = pageWidth - margin * 2
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://contract-analyser-iota.vercel.app'

  let y = 24

  // Header
  doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(17, 24, 39)
  doc.text('CONTRACT ANALYSER APP', pageWidth / 2, y, { align: 'center' }); y += 6
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(107, 114, 128)
  doc.text('Technical Overview  ·  Built by Marco Costa', pageWidth / 2, y, { align: 'center' }); y += 7
  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 8

  // Description
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(75, 85, 99)
  const desc = 'A full-stack web application that allows users to upload contract PDFs and receive a structured legal analysis generated by AI. Built as a portfolio demonstration of legal engineering and software development skills.'
  const descLines = doc.splitTextToSize(desc, contentWidth)
  doc.text(descLines, margin, y); y += descLines.length * 4.5 + 8

  // ── Flow diagram section heading ──
  doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(29, 78, 216)
  doc.text('APPLICATION FLOW', margin, y); y += 1.5
  doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 6

  // Flow diagram constants
  const bh = 10    // box height mm
  const br = 2     // box corner radius
  const fs = 7     // font size in boxes
  const lh = 16    // row height (box + gap)
  const c1x = margin + 10
  const c1w = 36
  const g1  = 6
  const c2x = c1x + c1w + g1
  const c2w = 48
  const g2  = 6
  const c3x = c2x + c2w + g2
  const c3w = 54

  const r1y = y
  const r2y = y + lh
  const r3y = y + lh * 2
  const r4y = y + lh * 3

  // Layer label helper
  const layerLabel = (label: string, ry: number) => {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(6); doc.setTextColor(180, 180, 180)
    doc.text(label, margin, ry + bh / 2, { baseline: 'middle' })
  }

  // Box helper
  const box = (x: number, bw: number, by: number, label: string, sub: string | null,
    blue: boolean, purple: boolean, teal: boolean, amber: boolean) => {
    if (blue)        { doc.setFillColor(219, 234, 254); doc.setDrawColor(147, 197, 253) }
    else if (purple) { doc.setFillColor(237, 233, 254); doc.setDrawColor(196, 181, 253) }
    else if (teal)   { doc.setFillColor(209, 250, 229); doc.setDrawColor(110, 231, 183) }
    else if (amber)  { doc.setFillColor(254, 243, 199); doc.setDrawColor(252, 211, 77)  }
    else             { doc.setFillColor(243, 244, 246); doc.setDrawColor(209, 213, 219) }
    doc.roundedRect(x, by, bw, bh, br, br, 'FD')
    doc.setFont('helvetica', 'bold'); doc.setFontSize(fs)
    if (blue)        doc.setTextColor(30, 64, 175)
    else if (purple) doc.setTextColor(109, 40, 217)
    else if (teal)   doc.setTextColor(4, 120, 87)
    else if (amber)  doc.setTextColor(146, 64, 14)
    else             doc.setTextColor(55, 65, 81)
    const ty = sub ? by + 3.5 : by + bh / 2
    doc.text(label, x + bw / 2, ty, { align: 'center', baseline: 'middle' })
    if (sub) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(107, 114, 128)
      doc.text(sub, x + bw / 2, by + 7, { align: 'center', baseline: 'middle' })
    }
  }

  // Horizontal arrow — label below
  const arrowH = (x1: number, x2: number, ay: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(x1, ay, x2 - 1, ay)
    doc.setFillColor(156, 163, 175)
    doc.triangle(x2, ay, x2 - 2, ay - 1, x2 - 2, ay + 1, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, (x1 + x2) / 2, ay + 2.5, { align: 'center' })
    }
    doc.setLineWidth(0.2)
  }

  // Vertical arrow — label to the right
  const arrowV = (ax: number, y1: number, y2: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(ax, y1, ax, y2 - 1)
    doc.setFillColor(156, 163, 175)
    doc.triangle(ax, y2, ax - 1, y2 - 2, ax + 1, y2 - 2, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, ax + 2, (y1 + y2) / 2, { align: 'left', baseline: 'middle' })
    }
    doc.setLineWidth(0.2)
  }

  // Left-pointing arrow — label below
  const arrowLeft = (x1: number, x2: number, ay: number, label: string | null) => {
    doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
    doc.line(x1, ay, x2 + 1, ay)
    doc.setFillColor(156, 163, 175)
    doc.triangle(x2, ay, x2 + 2, ay - 1, x2 + 2, ay + 1, 'F')
    if (label) {
      doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); doc.setTextColor(156, 163, 175)
      doc.text(label, (x1 + x2) / 2, ay + 2.5, { align: 'center' })
    }
    doc.setLineWidth(0.2)
  }

  doc.setLineWidth(0.2)

  // ROW 1 — Access
  layerLabel('Access', r1y)
  box(c1x, c1w, r1y, 'User', null, false, false, false, false)
  arrowH(c1x + c1w, c2x, r1y + bh / 2, 'email')
  box(c2x, c2w, r1y, 'Resend', 'sends access code', true, false, false, false)
  arrowH(c2x + c2w, c3x, r1y + bh / 2, 'access code')
  box(c3x, c3w, r1y, 'Supabase DB', 'stores access_codes', false, false, true, false)

  // ROW 2 — Analysis
  layerLabel('Analysis', r2y)
  arrowV(c1x + c1w / 2, r1y + bh, r2y, 'code + PDF')
  box(c1x, c1w, r2y, 'Next.js API', '/api/analisar', false, false, false, false)
  arrowH(c1x + c1w, c2x, r2y + bh / 2, 'validate')
  box(c2x, c2w, r2y, 'Supabase DB', 'checks code + count', false, false, true, false)
  arrowH(c2x + c2w, c3x, r2y + bh / 2, 'PDF')
  box(c3x, c3w, r2y, 'Anthropic API', 'Claude analyses PDF', false, true, false, false)

  // ROW 3 — Delivery
  layerLabel('Delivery', r3y)
  arrowV(c3x + c3w / 2, r2y + bh, r3y, 'analysis')
  box(c3x, c3w, r3y, 'jsPDF', 'generates PDF report', false, false, false, false)
  arrowLeft(c3x, c2x + c2w, r3y + bh / 2, 'PDF')
  box(c2x, c2w, r3y, 'Resend', 'emails PDF to user', true, false, false, false)
  arrowLeft(c2x, c1x + c1w, r3y + bh / 2, null)
  box(c1x, c1w, r3y, 'User inbox', 'analysis + tech', false, false, false, false)

  // ROW 4 — Storage
  layerLabel('Storage', r4y)
  arrowV(c1x + c1w / 2, r2y + bh, r4y, null)
  box(c1x, c1w, r4y, 'Supabase Storage', 'contract PDF', false, false, true, false)
  arrowH(c1x + c1w, c2x, r4y + bh / 2, null)
  box(c2x, c2w, r4y, 'Supabase DB', 'saves analysis', false, false, true, false)
  // dashed arrow to cron
  doc.setDrawColor(156, 163, 175); doc.setLineWidth(0.3)
  doc.setLineDashPattern([1, 1], 0)
  doc.line(c2x + c2w, r4y + bh / 2, c3x - 1, r4y + bh / 2)
  doc.setLineDashPattern([], 0)
  doc.setFillColor(156, 163, 175)
  doc.triangle(c3x, r4y + bh / 2, c3x - 2, r4y + bh / 2 - 1, c3x - 2, r4y + bh / 2 + 1, 'F')
  doc.setLineWidth(0.2)
  box(c3x, c3w, r4y, 'Vercel cron', 'deletes 3d / 30d', false, false, false, true)

  y = r4y + bh + 8

  // ── Tech stack sections ──
  const section = (title: string) => {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(29, 78, 216)
    doc.text(title.toUpperCase(), margin, y); y += 1.5
    doc.setDrawColor(219, 234, 254); doc.line(margin, y, pageWidth - margin, y); y += 5
  }

  const item = (label: string, detail: string) => {
    const colLabel = 52
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8.5); doc.setTextColor(17, 24, 39)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(75, 85, 99)
    const detailLines = doc.splitTextToSize(detail, contentWidth - colLabel)
    doc.text(detailLines, margin + colLabel, y); y += detailLines.length * 4.5 + 1.5
  }

  section('Frontend')
  item('Next.js 14', 'React framework with App Router, Server Components and API Routes')
  item('TypeScript', 'Typed JavaScript for reliability and maintainability')
  item('Tailwind CSS', 'Utility-first CSS framework for responsive design')
  item('React Markdown', 'Renders structured markdown output from Claude API')
  y += 3

  section('Backend & API')
  item('Next.js API Routes', 'Server-side endpoints for analysis, access control and email dispatch')
  item('Anthropic Claude API', 'claude-opus-4-5 — native PDF reading, structured legal analysis')
  item('Resend', 'Transactional email delivery (access code + analysis PDF)')
  item('jsPDF', 'Server-side PDF generation for analysis report and technical sheet')
  y += 3

  section('Infrastructure & Data')
  item('Vercel', 'Deployment platform with serverless functions and daily cron job')
  item('Supabase', 'PostgreSQL database (access codes, analyses) and file storage (PDFs)')
  item('Supabase Storage', 'Secure private bucket for uploaded contract PDFs (max 20 MB)')
  y += 3

  section('Key Features')
  const features = [
    'Access control via professional email + one-time code',
    'Email domain validation — blocks personal email providers',
    'Native PDF reading by Claude (no intermediate text extraction)',
    'Structured legal analysis across 8 sections',
    'Automatic PDF generation and email delivery to user',
    'Usage limits enforced per access code',
    'Automated data retention: analyses deleted after 3 days, codes after 30 days',
    'Admin panel with usage tracking and CSV export',
  ]
  for (const f of features) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(55, 65, 81)
    doc.text('•', margin, y)
    const wrapped = doc.splitTextToSize(f, contentWidth - 5)
    doc.text(wrapped, margin + 5, y); y += wrapped.length * 4.5 + 1
  }
  y += 4

  // Footer
  doc.setDrawColor(229, 231, 235); doc.line(margin, y, pageWidth - margin, y); y += 5
  doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(156, 163, 175)
  doc.text('Built by Marco Costa  ·  Legal Engineer  ·  For portfolio demonstration purposes', pageWidth / 2, y, { align: 'center' }); y += 4
  doc.setTextColor(29, 78, 216)
  doc.textWithLink(appUrl, pageWidth / 2, y, { url: appUrl, align: 'center' } as any)

  return Buffer.from(doc.output('arraybuffer'))
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const file = formData.get('file') as File
    const code = formData.get('code') as string
    const email = formData.get('email') as string
    const company = formData.get('company') as string

    if (!file || !code) {
      return NextResponse.json({ error: 'Missing required fields.' }, { status: 400 })
    }
    if (file.type !== 'application/pdf') {
      return NextResponse.json({ error: 'Please upload a PDF file.' }, { status: 400 })
    }
    if (file.size > 20 * 1024 * 1024) {
      return NextResponse.json({ error: 'File size exceeds 20MB limit.' }, { status: 400 })
    }

    const { data, error: codeError } = await supabaseAdmin
      .from('access_codes')
      .select('*')
      .eq('code', code.toUpperCase().trim())
      .eq('is_active', true)
      .single()

    if (codeError || !data) {
      return NextResponse.json({ error: 'Invalid access code.' }, { status: 403 })
    }
    if (data.analysis_count >= 1) {
      return NextResponse.json({ error: 'limit_reached' }, { status: 403 })
    }

    const arrayBuffer = await file.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)
    const base64Pdf = buffer.toString('base64')

    const message = await anthropic.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 3000,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'document',
              source: { type: 'base64', media_type: 'application/pdf', data: base64Pdf },
            },
            {
              type: 'text',
              text: `You are a senior attorney at a top-tier international law firm. Analyse the attached contract and produce a structured legal report.

STRICT FORMATTING RULES \u2014 follow exactly:
- Start the report with: **Legal report:** [contract title in plain text, not bold]
- NEVER use markdown tables. Tables are forbidden.
- Use bullet points (starting with -) for ALL lists and structured content.
- The only emoji allowed throughout the report is \u26a0\ufe0f for flags and warnings.
- In section 7 only, use a single small circle: \ud83d\udfe2 for low, \ud83d\udfe1 for medium, \ud83d\udd34 for high \u2014 followed by normal text (no caps lock).
- No other emojis anywhere.
- All section headings in sentence case (not caps lock).
- Consistent font size throughout \u2014 no oversized headings.
- Be concise, precise, and legally rigorous.

---

## Executive summary

- **Contract type:** [type]
- **Parties:** [Party A] / [Party B]
- **Purpose:** [one sentence]
- **Duration:** [dates]
- **Value:** [amount if applicable]
- **Overall risk:** [low / medium / high] \u2014 [one sentence justification]

---

## 1. Parties involved

- **[Party name]** \u2014 [legal status], [role], [NIF/registration if present]
- **[Party name]** \u2014 [legal status], [role], [NIF/registration if present]
- \u26a0\ufe0f [Flag any missing or unclear identification]

---

## 2. Main obligations

**[Party A]:**
- [obligation]
- [obligation]

**[Party B]:**
- [obligation]
- [obligation]

- \u26a0\ufe0f [Flag any critical gaps in obligations]

---

## 3. Termination clauses

- **Trigger:** [condition]
- **Notice period:** [duration]
- **Cure period:** [duration]
- **Effect:** [retroactive / non-retroactive]
- \u26a0\ufe0f **Missing provisions:** [list gaps]
- \u26a0\ufe0f **Undefined terms:** [flag any vague trigger language]

---

## 4. Liability

- **Liability cap:** [present / absent]
- **Consequential damages exclusion:** [present / absent]
- **Indemnification:** [present / absent]
- **Insurance requirements:** [present / absent]
- \u26a0\ufe0f **Critical gaps:** [list]

---

## 5. Risk register

**High \u2014 requires immediate attention before signing:**
- [Issue] \u2014 [one-line impact]

**Medium \u2014 should be negotiated:**
- [Issue] \u2014 [one-line impact]

**Low \u2014 minor points:**
- [Issue] \u2014 [one-line impact]

---

## 6. Key dates and deadlines

- **Execution date:** [date]
- **Start date:** [date]
- **End date:** [date]
- **Payment dates:** [specified / not specified]
- **Notice periods:** [duration]
- **Auto-renewal:** [present / absent]
- \u26a0\ufe0f **Missing deadlines:** [list]

---

## 7. Overall risk assessment

\ud83d\udfe2 Low / \ud83d\udfe1 Medium / \ud83d\udd34 High

- [Justification point 1]
- [Justification point 2]
- [Justification point 3]

---

## 8. Recommended improvements

- **[Issue]:** [specific recommended clause language or action]
- **[Issue]:** [specific recommended clause language or action]`
            }
          ]
        }
      ]
    })

    const analysisResult = message.content[0].type === 'text'
      ? message.content[0].text
      : 'Analysis could not be completed.'

    const generatedDate = new Date().toLocaleString('en-GB')

    const analysisPdfBuffer = generateAnalysisPdf(analysisResult, generatedDate)
    const techSheetBuffer = generateTechSheetPdf()

    const fileName = `${code}-${Date.now()}.pdf`
    await supabaseAdmin.storage
      .from('contracts')
      .upload(fileName, buffer, { contentType: 'application/pdf', upsert: false })

    await supabaseAdmin
      .from('access_codes')
      .update({ analysis_count: data.analysis_count + 1, last_accessed_at: new Date().toISOString() })
      .eq('code', code.toUpperCase().trim())

    await supabaseAdmin
      .from('analyses')
      .insert({
        access_code: code.toUpperCase().trim(),
        email,
        company,
        contract_text: '',
        analysis_result: analysisResult,
      })

    if (email) {
      await resend.emails.send({
        from: 'Contract Analyser <contractanalyzer@lawper.pt>',
        to: email,
        subject: 'Your contract analysis',
        attachments: [
          { filename: 'contract-analysis.pdf', content: analysisPdfBuffer.toString('base64') },
          { filename: 'app-tech-stack.pdf', content: techSheetBuffer.toString('base64') },
        ],
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 48px 24px;">

          <table cellpadding="0" cellspacing="0" border="0" style="margin-bottom: 28px; padding-bottom: 20px; border-bottom: 1px solid #f3f4f6; width: 100%;">
            <tr>
              <td style="width: 40px; vertical-align: middle;">
                <table cellpadding="0" cellspacing="0" border="0" style="width: 32px; height: 32px; background: #1d4ed8; border-radius: 6px;">
                  <tr>
                    <td style="text-align: center; vertical-align: middle; font-family: Arial, sans-serif; font-size: 11px; font-weight: 700; color: white; letter-spacing: 1px;">CA</td>
                  </tr>
                </table>
              </td>
              <td style="vertical-align: middle; padding-left: 10px; font-family: Arial, sans-serif; font-size: 14px; font-weight: 700; color: #111827;">Contract Analyser</td>
            </tr>
          </table>

            <p style="font-size: 14px; color: #111827; margin: 0 0 16px;">Hi,</p>

            <p style="font-size: 14px; color: #111827; margin: 0 0 16px;">Please find your contract analysis report attached to this email as a PDF.</p>

            <p style="font-size: 14px; color: #111827; margin: 0 0 32px;">I have also included a one-page technical overview of the application, in case you find it relevant.</p>

            <p style="font-size: 14px; color: #111827; margin: 0 0 24px;">Best,<br/>Marco Costa</p>

            <div style="border-top: 1px solid #e5e7eb; padding-top: 16px;">
              <p style="font-size: 11px; color: #9ca3af; margin: 0; line-height: 1.6;">
                <span style="font-weight: 700; color: #6b7280;">Disclaimer:</span> This analysis is generated by AI for informational purposes only. It does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified lawyer.
              </p>
            </div>

          </div>
        `
      })
    }

    await resend.emails.send({
      from: 'Contract Analyser <contractanalyzer@lawper.pt>',
      to: process.env.OPERATOR_EMAIL!,
      subject: `New analysis - ${company || 'Unknown'} (${email})`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
          <h2 style="color: #1d4ed8;">New Contract Analysis</h2>
          <table style="width: 100%; border-collapse: collapse; margin: 24px 0;">
            <tr><td style="padding: 8px; background: #f3f4f6; font-weight: bold; width: 30%;">Email</td><td style="padding: 8px;">${email}</td></tr>
            <tr><td style="padding: 8px; background: #f3f4f6; font-weight: bold;">Company</td><td style="padding: 8px;">${company}</td></tr>
            <tr><td style="padding: 8px; background: #f3f4f6; font-weight: bold;">Date</td><td style="padding: 8px;">${generatedDate}</td></tr>
            <tr><td style="padding: 8px; background: #f3f4f6; font-weight: bold;">Code</td><td style="padding: 8px;">${code}</td></tr>
          </table>
          <p style="color: #6b7280; font-size: 12px; margin-top: 24px;">Contract Analyser &middot; Marco Costa</p>
        </div>
      `
    })

    return NextResponse.json({ success: true, analysis: analysisResult })

  } catch (error) {
    console.error('Error analysing contract:', error)
    return NextResponse.json({ error: 'Internal error. Please try again.' }, { status: 500 })
  }
}
